// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/emptySeqEx:1.0
//
final public class emptySeqExHolder implements org.omg.CORBA.portable.Streamable
{
    public emptySeqEx value;

    public
    emptySeqExHolder()
    {
    }

    public
    emptySeqExHolder(emptySeqEx initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = emptySeqExHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        emptySeqExHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return emptySeqExHelper.type();
    }
}
