// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/Invitation:1.0
//
public abstract class InvitationPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               InvitationOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:de/cwrose/disical/corba/disiorb/Invitation:1.0",
    };

    public Invitation
    _this()
    {
        return InvitationHelper.narrow(super._this_object());
    }

    public Invitation
    _this(org.omg.CORBA.ORB orb)
    {
        return InvitationHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "delete",
            "destroy",
            "getAllInvited",
            "getAllNotifiedInv",
            "getDescription",
            "getEndTime",
            "getFromUser",
            "getLocation",
            "getStartTime",
            "getSubject",
            "invite",
            "persist",
            "setDescription",
            "setEndTime",
            "setFromUser",
            "setLocation",
            "setStartTime",
            "setSubject"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        switch(_ob_index)
        {
        case 0: // delete
            return _OB_op_delete(in, handler);

        case 1: // destroy
            return _OB_op_destroy(in, handler);

        case 2: // getAllInvited
            return _OB_op_getAllInvited(in, handler);

        case 3: // getAllNotifiedInv
            return _OB_op_getAllNotifiedInv(in, handler);

        case 4: // getDescription
            return _OB_op_getDescription(in, handler);

        case 5: // getEndTime
            return _OB_op_getEndTime(in, handler);

        case 6: // getFromUser
            return _OB_op_getFromUser(in, handler);

        case 7: // getLocation
            return _OB_op_getLocation(in, handler);

        case 8: // getStartTime
            return _OB_op_getStartTime(in, handler);

        case 9: // getSubject
            return _OB_op_getSubject(in, handler);

        case 10: // invite
            return _OB_op_invite(in, handler);

        case 11: // persist
            return _OB_op_persist(in, handler);

        case 12: // setDescription
            return _OB_op_setDescription(in, handler);

        case 13: // setEndTime
            return _OB_op_setEndTime(in, handler);

        case 14: // setFromUser
            return _OB_op_setFromUser(in, handler);

        case 15: // setLocation
            return _OB_op_setLocation(in, handler);

        case 16: // setStartTime
            return _OB_op_setStartTime(in, handler);

        case 17: // setSubject
            return _OB_op_setSubject(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_delete(org.omg.CORBA.portable.InputStream in,
                  org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            delete();
            out = handler.createReply();
        }
        catch(jdoPersistenceEx _ob_ex)
        {
            out = handler.createExceptionReply();
            jdoPersistenceExHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_destroy(org.omg.CORBA.portable.InputStream in,
                   org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        destroy();
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getAllInvited(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            Invited[] _ob_r = getAllInvited();
            out = handler.createReply();
            seqInvitedHelper.write(out, _ob_r);
        }
        catch(jdoPersistenceEx _ob_ex)
        {
            out = handler.createExceptionReply();
            jdoPersistenceExHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getAllNotifiedInv(org.omg.CORBA.portable.InputStream in,
                             org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            Invited[] _ob_r = getAllNotifiedInv();
            out = handler.createReply();
            seqInvitedHelper.write(out, _ob_r);
        }
        catch(jdoPersistenceEx _ob_ex)
        {
            out = handler.createExceptionReply();
            jdoPersistenceExHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getDescription(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_r = getDescription();
        out = handler.createReply();
        out.write_string(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getEndTime(org.omg.CORBA.portable.InputStream in,
                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        long _ob_r = getEndTime();
        out = handler.createReply();
        out.write_longlong(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getFromUser(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            User _ob_r = getFromUser();
            out = handler.createReply();
            UserHelper.write(out, _ob_r);
        }
        catch(jdoPersistenceEx _ob_ex)
        {
            out = handler.createExceptionReply();
            jdoPersistenceExHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getLocation(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_r = getLocation();
        out = handler.createReply();
        out.write_string(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getStartTime(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        long _ob_r = getStartTime();
        out = handler.createReply();
        out.write_longlong(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_getSubject(org.omg.CORBA.portable.InputStream in,
                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_r = getSubject();
        out = handler.createReply();
        out.write_string(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_invite(org.omg.CORBA.portable.InputStream in,
                  org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            User _ob_a0 = UserHelper.read(in);
            invite(_ob_a0);
            out = handler.createReply();
        }
        catch(jdoPersistenceEx _ob_ex)
        {
            out = handler.createExceptionReply();
            jdoPersistenceExHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_persist(org.omg.CORBA.portable.InputStream in,
                   org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        boolean _ob_r = persist();
        out = handler.createReply();
        out.write_boolean(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_setDescription(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_a0 = in.read_string();
        setDescription(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_setEndTime(org.omg.CORBA.portable.InputStream in,
                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        long _ob_a0 = in.read_longlong();
        setEndTime(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_setFromUser(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        User _ob_a0 = UserHelper.read(in);
        setFromUser(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_setLocation(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_a0 = in.read_string();
        setLocation(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_setStartTime(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        long _ob_a0 = in.read_longlong();
        setStartTime(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_setSubject(org.omg.CORBA.portable.InputStream in,
                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_a0 = in.read_string();
        setSubject(_ob_a0);
        out = handler.createReply();
        return out;
    }
}
