// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/Invited:1.0
//
final public class InvitedHolder implements org.omg.CORBA.portable.Streamable
{
    public Invited value;

    public
    InvitedHolder()
    {
    }

    public
    InvitedHolder(Invited initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = InvitedHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        InvitedHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return InvitedHelper.type();
    }
}
