// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/Invitation:1.0
//
/***/

public interface InvitationOperations
{
    //
    // IDL:de/cwrose/disical/corba/disiorb/Invitation/fromUser:1.0
    //
    /***/

    User
    fromUser();

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invitation/toUser:1.0
    //
    /***/

    User[]
    toUser();

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invitation/InvitationDate:1.0
    //
    /***/

    Date
    InvitationDate();

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invitation/getStatus:1.0
    //
    /***/

    short
    getStatus();

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invitation/setStatus:1.0
    //
    /***/

    void
    setStatus(short newStatus);
}
