// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/Invited:1.0
//
/***/

public interface InvitedOperations
{
    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/getInvitation:1.0
    //
    /***/

    Invitation
    getInvitation()
        throws jdoPersistenceEx;

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/getUser:1.0
    //
    /***/

    User
    getUser()
        throws jdoPersistenceEx;

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/accept:1.0
    //
    /***/

    void
    accept()
        throws jdoPersistenceEx;

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/reject:1.0
    //
    /***/

    void
    reject()
        throws jdoPersistenceEx;

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/status:1.0
    //
    /***/

    short
    status();

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/persist:1.0
    //
    /***/

    boolean
    persist();

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/delete:1.0
    //
    /***/

    void
    delete()
        throws jdoPersistenceEx;

    //
    // IDL:de/cwrose/disical/corba/disiorb/Invited/destroy:1.0
    //
    /***/

    void
    destroy();
}
