// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/jdoPersistenceEx:1.0
//
final public class jdoPersistenceExHolder implements org.omg.CORBA.portable.Streamable
{
    public jdoPersistenceEx value;

    public
    jdoPersistenceExHolder()
    {
    }

    public
    jdoPersistenceExHolder(jdoPersistenceEx initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = jdoPersistenceExHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        jdoPersistenceExHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return jdoPersistenceExHelper.type();
    }
}
