// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/seqDate:1.0
//
final public class seqDateHolder implements org.omg.CORBA.portable.Streamable
{
    public Date[] value;

    public
    seqDateHolder()
    {
    }

    public
    seqDateHolder(Date[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = seqDateHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        seqDateHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return seqDateHelper.type();
    }
}
