// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/seqInvited:1.0
//
final public class seqInvitedHolder implements org.omg.CORBA.portable.Streamable
{
    public Invited[] value;

    public
    seqInvitedHolder()
    {
    }

    public
    seqInvitedHolder(Invited[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = seqInvitedHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        seqInvitedHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return seqInvitedHelper.type();
    }
}
