// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/seqInvitation:1.0
//
final public class seqInvitationHolder implements org.omg.CORBA.portable.Streamable
{
    public Invitation[] value;

    public
    seqInvitationHolder()
    {
    }

    public
    seqInvitationHolder(Invitation[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = seqInvitationHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        seqInvitationHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return seqInvitationHelper.type();
    }
}
