// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/Server:1.0
//
/***/

public interface ServerOperations
{
    //
    // IDL:de/cwrose/disical/corba/disiorb/Server/createUser:1.0
    //
    /***/

    User
    createUser(String login,
               String name,
               String pwd,
               String email);

    //
    // IDL:de/cwrose/disical/corba/disiorb/Server/login:1.0
    //
    /***/

    User
    login(String login,
          String pwd);
}
