// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/Server:1.0
//
public abstract class ServerPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               ServerOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:de/cwrose/disical/corba/disiorb/Server:1.0",
    };

    public Server
    _this()
    {
        return ServerHelper.narrow(super._this_object());
    }

    public Server
    _this(org.omg.CORBA.ORB orb)
    {
        return ServerHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "createUser",
            "destroy",
            "login"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        switch(_ob_index)
        {
        case 0: // createUser
            return _OB_op_createUser(in, handler);

        case 1: // destroy
            return _OB_op_destroy(in, handler);

        case 2: // login
            return _OB_op_login(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_createUser(org.omg.CORBA.portable.InputStream in,
                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = in.read_string();
            String _ob_a1 = in.read_string();
            String _ob_a2 = in.read_string();
            String _ob_a3 = in.read_string();
            User _ob_r = createUser(_ob_a0, _ob_a1, _ob_a2, _ob_a3);
            out = handler.createReply();
            UserHelper.write(out, _ob_r);
        }
        catch(jdoPersistenceEx _ob_ex)
        {
            out = handler.createExceptionReply();
            jdoPersistenceExHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_destroy(org.omg.CORBA.portable.InputStream in,
                   org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        destroy();
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_login(org.omg.CORBA.portable.InputStream in,
                 org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = in.read_string();
            String _ob_a1 = in.read_string();
            User _ob_r = login(_ob_a0, _ob_a1);
            out = handler.createReply();
            UserHelper.write(out, _ob_r);
        }
        catch(wrongPwEx _ob_ex)
        {
            out = handler.createExceptionReply();
            wrongPwExHelper.write(out, _ob_ex);
        }
        catch(jdoPersistenceEx _ob_ex)
        {
            out = handler.createExceptionReply();
            jdoPersistenceExHelper.write(out, _ob_ex);
        }
        return out;
    }
}
