// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/User:1.0
//
final public class UserHolder implements org.omg.CORBA.portable.Streamable
{
    public User value;

    public
    UserHolder()
    {
    }

    public
    UserHolder(User initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = UserHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        UserHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return UserHelper.type();
    }
}
