// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/wrongPwEx:1.0
//
final public class wrongPwExHolder implements org.omg.CORBA.portable.Streamable
{
    public wrongPwEx value;

    public
    wrongPwExHolder()
    {
    }

    public
    wrongPwExHolder(wrongPwEx initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = wrongPwExHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        wrongPwExHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return wrongPwExHelper.type();
    }
}
