// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package de.cwrose.disical.corba.disiorb;

//
// IDL:de/cwrose/disical/corba/disiorb/wrongPwEx:1.0
//
/***/

final public class wrongPwEx extends org.omg.CORBA.UserException
{
    private static final String _ob_id = "IDL:de/cwrose/disical/corba/disiorb/wrongPwEx:1.0";

    public
    wrongPwEx()
    {
        super(_ob_id);
    }

    public
    wrongPwEx(String _reason)
    {
        super(_ob_id + " " + _reason);
    }
}
