/*
 * DateChooser.java
 *
 * Created on 31. Januar 2002, 04:26
 */

package de.cwrose.disical.ui;

/**
 *
 * @author  user1
 */

import java.util.*;

public class DateChooser extends javax.swing.JDialog {
  public boolean cancel = false;

   

    /** Creates new form DateChooser */
    public DateChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.hours.setMinimum(0);
        this.hours.setMaximum(23);
        this.min.setMinimum(0);
        this.min.setMaximum(59);
        this.hours.setValue(jCalendar1.getCalendar().get(Calendar.HOUR));
        this.min.setValue(jCalendar1.getCalendar().get(Calendar.MINUTE));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jCalendar1 = new CalendarBean.JCalendar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        hours = new CalendarBean.JSpinField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        min = new CalendarBean.JSpinField();
        jPanel1 = new javax.swing.JPanel();
        okbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(jCalendar1, gridBagConstraints1);
        
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));
        
        jLabel1.setText("h");
        jPanel2.add(jLabel1);
        
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        hours.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hoursPropertyChange(evt);
            }
        });
        
        jPanel4.add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));
        
        jPanel2.add(jPanel4);
        
        jLabel2.setText("min");
        jPanel2.add(jLabel2);
        
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        min.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                minPropertyChange(evt);
            }
        });
        
        jPanel3.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, -1));
        
        jPanel2.add(jPanel3);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        getContentPane().add(jPanel2, gridBagConstraints1);
        
        okbutton.setText("ok");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });
        
        jPanel1.add(okbutton);
        
        cancelbutton.setText("cancel");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        
        jPanel1.add(cancelbutton);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        getContentPane().add(jPanel1, gridBagConstraints1);
        
        pack();
    }//GEN-END:initComponents

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        // Add your handling code here:
        
       System.out.println (this.jCalendar1.getCalendar().getTime().toLocaleString());
    }//GEN-LAST:event_jCalendar1PropertyChange

    private void minPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_minPropertyChange
        this.jCalendar1.getCalendar().set(Calendar.MINUTE, min.getValue());
    }//GEN-LAST:event_minPropertyChange

    private void hoursPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hoursPropertyChange
        // Add your handling code here:
        this.jCalendar1.getCalendar().set(Calendar.HOUR, hours.getValue());
    }//GEN-LAST:event_hoursPropertyChange

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
        // Add your handling code here:
        cancel = true;
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // Add your handling code here:
        cancel = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okbuttonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        cancel = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new DateChooser(new javax.swing.JFrame(), true).show();
        
    }
    
    public Calendar getCalendar() {
        return this.jCalendar1.getCalendar();
     
      
    }
    
    public void setCalendar(Calendar cal) {
        this.jCalendar1.setCalendar(cal);
        this.hours.setValue(jCalendar1.getCalendar().get(Calendar.HOUR));
        this.min.setValue(jCalendar1.getCalendar().get(Calendar.MINUTE));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarBean.JCalendar jCalendar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private CalendarBean.JSpinField hours;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private CalendarBean.JSpinField min;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okbutton;
    private javax.swing.JButton cancelbutton;
    // End of variables declaration//GEN-END:variables

}
