/*
 * DateEditor.java
 *
 * Created on 26. Januar 2002, 18:30
 */

package de.cwrose.disical.ui;

import java.util.*;

/**
 *
 * @author  user1
 */
public class DateEditor extends javax.swing.JDialog {
    public boolean cancel = false;
    public Calendar startcal= null;
    public Calendar stopcal = null;
    public String event = "";
    public String location = "";
    public String commment = "";
   
    
    /** Creates new form DateEditor */
    public DateEditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        
        
        
        
        initComponents();
        this.setSize(300, 400);
        myInit();
    }
    
    public void myInit() {
        startcal = Calendar.getInstance();
        stopcal = Calendar.getInstance();
        this.startTime.setText(startcal.getTime().toLocaleString());
        this.stopTime.setText(stopcal.getTime().toLocaleString());
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        startTime = new javax.swing.JLabel();
        startchange = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        stopLabel = new javax.swing.JLabel();
        stopTime = new javax.swing.JLabel();
        stopchange = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        commentText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        locationText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        eventText = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        okbutton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        setTitle("Eventeditor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));
        
        startLabel.setText("Starttime:");
        jPanel2.add(startLabel);
        
        startTime.setText("jLabel6");
        startTime.setForeground(java.awt.Color.black);
        jPanel2.add(startTime);
        
        startchange.setText("change");
        startchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startchangeActionPerformed(evt);
            }
        });
        
        jPanel2.add(startchange);
        
        jPanel1.add(jPanel2);
        
        stopLabel.setText("Stoptime:");
        jPanel3.add(stopLabel);
        
        stopTime.setText("jLabel6");
        stopTime.setForeground(java.awt.Color.black);
        jPanel3.add(stopTime);
        
        stopchange.setText("change");
        stopchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        jPanel3.add(stopchange);
        
        jPanel1.add(jPanel3);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 8;
        getContentPane().add(jPanel1, gridBagConstraints1);
        
        jPanel4.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints3;
        
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        commentText.setPreferredSize(new java.awt.Dimension(10, 17));
        commentText.setMinimumSize(new java.awt.Dimension(10, 17));
        jPanel5.add(commentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 180, 140));
        
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 1;
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanel4.add(jPanel5, gridBagConstraints3);
        
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setText("Comment:");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 0;
        jPanel4.add(jLabel3, gridBagConstraints3);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 9;
        gridBagConstraints1.gridwidth = 15;
        getContentPane().add(jPanel4, gridBagConstraints1);
        
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        
        jLabel5.setText("Location:");
        jPanel6.add(jLabel5);
        
        locationText.setText(" ");
        locationText.setPreferredSize(new java.awt.Dimension(50, 21));
        locationText.setMinimumSize(new java.awt.Dimension(50, 21));
        locationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTextActionPerformed(evt);
            }
        });
        
        jPanel6.add(locationText);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 6;
        getContentPane().add(jPanel6, gridBagConstraints1);
        
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        
        jLabel6.setText("Event:");
        jPanel7.add(jLabel6);
        
        eventText.setText(" ");
        eventText.setPreferredSize(new java.awt.Dimension(50, 21));
        eventText.setMinimumSize(new java.awt.Dimension(50, 21));
        jPanel7.add(eventText);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 5;
        getContentPane().add(jPanel7, gridBagConstraints1);
        
        okbutton.setText("ok");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });
        
        jPanel8.add(okbutton);
        
        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        
        jPanel8.add(cancelButton);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 10;
        getContentPane().add(jPanel8, gridBagConstraints1);
        
        pack();
    }//GEN-END:initComponents
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        cancel = true;
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // Add your handling code here:
        this.event = this.eventText.getText();
        this.location = this.locationText.getText();
        this.commment = this.commentText.getText();
        this.cancel = false;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okbuttonActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        DateChooser dlg = new DateChooser( new java.awt.Frame(), true);
        dlg.setCalendar(this.stopcal);
        dlg.show();
        this.stopcal = dlg.getCalendar();
        this.stopTime.setText( stopcal.getTime().toLocaleString());
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void locationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_locationTextActionPerformed
    
    private void stopchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopchangeActionPerformed
        // Add your handling code here:
        
        
    }//GEN-LAST:event_stopchangeActionPerformed
    
    private void startchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startchangeActionPerformed
        // Add your handling code here:
        DateChooser dlg = new DateChooser( new java.awt.Frame(), true );
        dlg.setCalendar(this.startcal);
        dlg.show();
        this.startcal = dlg.getCalendar();
        System.out.println(startcal.getTime().toLocaleString());
        this.startTime.setText( startcal.getTime().toLocaleString());
        this.repaint();
    }//GEN-LAST:event_startchangeActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        cancel = true;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DateEditor(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel startTime;
    private javax.swing.JButton startchange;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel stopLabel;
    private javax.swing.JLabel stopTime;
    private javax.swing.JButton stopchange;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextArea commentText;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField locationText;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField eventText;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton okbutton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables
    
}
