/*
 * DisicalMainFrame.java
 *
 * Created on 12. Januar 2002, 16:14
 */

package de.cwrose.disical.ui;

/**
 *
 * @author  user1
 */

import java.awt.*;
import java.awt.event.*;
import de.cwrose.disical.corba.*;
import de.cwrose.disical.corba.disiorb.*;
import de.cwrose.disical.corba.Exceptions.*;

public class DisicalMainFrame extends javax.swing.JFrame implements ActionListener {
    boolean online = false; // true if user is logged in
    Server server = null;
    DisicalCli client = null;
    User user = null;
    String[] args = null;
    
    /** Creates new form DisicalMainFrame */
    public DisicalMainFrame() {
        System.out.println("Huraa ich bin da");
        initComponents();
        setSize(640,480);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenuItem();
        registerMenu = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        configMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        
        fileMenu.setText("File");
        loginMenu.setText("login");
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });
        
        fileMenu.add(loginMenu);
        registerMenu.setText("register");
        registerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMenuActionPerformed(evt);
            }
        });
        
        fileMenu.add(registerMenu);
        logoutMenu.setText("logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        
        fileMenu.add(logoutMenu);
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        
        fileMenu.add(exitMenuItem);
        menuBar.add(fileMenu);
        configMenu.setText("Options");
        jMenuItem3.setText("Server");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        
        configMenu.add(jMenuItem3);
        menuBar.add(configMenu);
        helpMenu.setText("Help");
        contentMenuItem.setText("Contents");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        
        helpMenu.add(contentMenuItem);
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        
        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);
        
        setJMenuBar(menuBar);
        pack();
    }//GEN-END:initComponents
    
    private void registerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMenuActionPerformed
        
        boolean cancel = false;
        RegisterDialog dlg =   new RegisterDialog(new javax.swing.JFrame(), true);
        while ( ! online &&  ! cancel) {
            dlg.show();
            cancel = dlg.cancel;
            if (!cancel) {
           
                if (server == null) {
                    client = new DisicalCli(new String[0]);                    
                    try {
                        server = client.getServer();
                         online = true;
                         user =     server.createUser(dlg.login, dlg.name, dlg.password,  dlg.email);
                         System.out.println(cancel);
                         
                         try {
                             new SessionFrame(user.listAllDatesByTime()).show();
                         } catch ( Exception e)  {
                             new SessionFrame(new Date[0]).show();
                             e.printStackTrace(System.out);
                         }
                    }
                    catch (jdoPersistenceEx e) {
                        System.out.println(e.toString());
                        e.printStackTrace(System.out);
                    }
                }
               
            }
        }
        
    }//GEN-LAST:event_registerMenuActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        // Add your handling code here:
        if (online && user != null) {
            user.destroy();
            online = false;
            user = null;
        }
    }//GEN-LAST:event_logoutMenuActionPerformed
    
    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
        boolean cancel = false;
        LoginDialog dlg = new LoginDialog(new javax.swing.JFrame(), true);
        while ( ! online &&  ! cancel) {
            dlg.show();
            cancel = dlg.cancel;
            System.out.println(cancel);
            dlg.setMessage(dlg.login + " " + dlg.password);
            
            
            
        }
        
        // Add your handling code here:
    }//GEN-LAST:event_loginMenuActionPerformed
    
    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_copyMenuItemActionPerformed
    
    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_contentMenuItemActionPerformed
    
    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        
        // Add your handling code here:
        new AboutDialog(new javax.swing.JFrame(), true).show();
    }//GEN-LAST:event_aboutMenuItemActionPerformed
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DisicalMainFrame().show();
       // this.args = args;
    }
    
    public void actionPerformed(java.awt.event.ActionEvent actionEvent) {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenuItem registerMenu;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu configMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    // End of variables declaration//GEN-END:variables
    
}
