/*
 * InvitationDialog.java
 *
 * Created on 26. Januar 2002, 16:24
 */

package de.cwrose.disical.ui;

/**
 *
 * @author  user1
 */
public class InvitationDialog extends javax.swing.JDialog {

    /** Creates new form InvitationDialog */
    public InvitationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jList3 = new javax.swing.JList();
        jList1 = new javax.swing.JList();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 260));
        jPanel1.setMinimumSize(new java.awt.Dimension(390, 260));
        jLabel2.setText("users:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));
        
        jLabel3.setText("invited users:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));
        
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "", "", "", "", "", "", "", "", "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jPanel1.add(jList3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 120, 130));
        
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "", "", "", "", "", "", "", "", "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jPanel1.add(jList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 130));
        
        addButton.setText("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));
        
        removeButton.setText("remove");
        jPanel1.add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));
        
        jButton3.setText("ok");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        
        jButton4.setText("cancel");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));
        
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new InvitationDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList3;
    private javax.swing.JList jList1;
    private javax.swing.JButton addButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
