/*
 * MainFrame.java
 *
 * Created on 22. Januar 2002, 20:23
 */

package de.cwrose.disical.ui;

/**
 *
 * @author  conny
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame () {
        
        initComponents();
        setSize(640,480);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents ()//GEN-BEGIN:initComponents
    {
        menuBar = new javax.swing.JMenuBar ();
        serverMenu = new javax.swing.JMenu ();
        loginMenuItem = new javax.swing.JMenuItem ();
        logoutMenuIntem = new javax.swing.JMenuItem ();
        registerMenuItem = new javax.swing.JMenuItem ();
        editMenu = new javax.swing.JMenu ();
        cutMenuItem = new javax.swing.JMenuItem ();
        copyMenuItem = new javax.swing.JMenuItem ();
        pasteMenuItem = new javax.swing.JMenuItem ();
        deleteMenuItem = new javax.swing.JMenuItem ();
        optionsMenu = new javax.swing.JMenu ();
        helpMenu = new javax.swing.JMenu ();
        contentMenuItem = new javax.swing.JMenuItem ();
        aboutMenuItem = new javax.swing.JMenuItem ();
        desktopPane = new javax.swing.JDesktopPane ();
        
        serverMenu.setText ("Server");
        loginMenuItem.setText ("login");
        loginMenuItem.addActionListener (new java.awt.event.ActionListener ()
        {
            public void actionPerformed (java.awt.event.ActionEvent evt)
            {
                loginMenuItemActionPerformed (evt);
            }
        });
        
        serverMenu.add (loginMenuItem);
        logoutMenuIntem.setText ("logout");
        logoutMenuIntem.addActionListener (new java.awt.event.ActionListener ()
        {
            public void actionPerformed (java.awt.event.ActionEvent evt)
            {
                logoutMenuIntemActionPerformed (evt);
            }
        });
        
        serverMenu.add (logoutMenuIntem);
        registerMenuItem.setText ("register");
        serverMenu.add (registerMenuItem);
        menuBar.add (serverMenu);
        editMenu.setText ("Edit");
        cutMenuItem.setText ("Cut");
        editMenu.add (cutMenuItem);
        copyMenuItem.setText ("Copy");
        editMenu.add (copyMenuItem);
        pasteMenuItem.setText ("Paste");
        editMenu.add (pasteMenuItem);
        deleteMenuItem.setText ("Delete");
        editMenu.add (deleteMenuItem);
        menuBar.add (editMenu);
        optionsMenu.setText ("Options");
        menuBar.add (optionsMenu);
        helpMenu.setText ("Help");
        contentMenuItem.setText ("Contents");
        helpMenu.add (contentMenuItem);
        aboutMenuItem.setText ("About");
        aboutMenuItem.addActionListener (new java.awt.event.ActionListener ()
        {
            public void actionPerformed (java.awt.event.ActionEvent evt)
            {
                aboutMenuItemActionPerformed (evt);
            }
        });
        
        helpMenu.add (aboutMenuItem);
        menuBar.add (helpMenu);
        
        addWindowListener (new java.awt.event.WindowAdapter ()
        {
            public void windowClosing (java.awt.event.WindowEvent evt)
            {
                exitForm (evt);
            }
        });
        
        getContentPane ().add (desktopPane, java.awt.BorderLayout.CENTER);
        
        setJMenuBar (menuBar);
        pack ();
    }//GEN-END:initComponents

    private void logoutMenuIntemActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_logoutMenuIntemActionPerformed
    {//GEN-HEADEREND:event_logoutMenuIntemActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_logoutMenuIntemActionPerformed

    private void loginMenuItemActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginMenuItemActionPerformed
    {//GEN-HEADEREND:event_loginMenuItemActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void aboutMenuItemActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutMenuItemActionPerformed
    {//GEN-HEADEREND:event_aboutMenuItemActionPerformed
       new AboutDialog (new javax.swing.JFrame (), true).show ();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new MainFrame ().show ();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu serverMenu;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoutMenuIntem;
    private javax.swing.JMenuItem registerMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    // End of variables declaration//GEN-END:variables

}
