/*
 * RegisterDialog.java
 *
 * Created on 26. Januar 2002, 16:48
 */

package de.cwrose.disical.ui;

/**
 *
 * @author  user1
 */
public class RegisterDialog extends javax.swing.JDialog {

    /** Creates new form RegisterDialog */
    public RegisterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jpasswordConfirmField = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        setTitle("New Disical User");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jPanel2.setLayout(new java.awt.GridLayout(5, 2));
        
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 80));
        jLabel6.setText("Name:");
        jPanel2.add(jLabel6);
        
        jPanel2.add(jTextField2);
        
        jLabel7.setText("Login:");
        jPanel2.add(jLabel7);
        
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        
        jPanel2.add(jTextField4);
        
        jLabel8.setText("Email:");
        jPanel2.add(jLabel8);
        
        jPanel2.add(jTextField3);
        
        jLabel10.setText("Password confirm:");
        jPanel2.add(jLabel10);
        
        jPanel2.add(passwordField);
        
        jLabel9.setText("Password:");
        jPanel2.add(jLabel9);
        
        jpasswordConfirmField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordConfirmFieldActionPerformed(evt);
            }
        });
        
        jPanel2.add(jpasswordConfirmField);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.ipady = 52;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints1);
        
        okButton.setText("ok");
        jPanel3.add(okButton);
        
        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        
        jPanel3.add(cancelButton);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 10;
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(jPanel3, gridBagConstraints1);
        
        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jpasswordConfirmFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordConfirmFieldActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jpasswordConfirmFieldActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new RegisterDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jpasswordConfirmField;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables

}
